# Copyright 2008, Jeffrey Regier, jeff [at] stat [dot] berkeley [dot] edu

# This file is part of Author-Dedupe.
#
# Author-Dedupe is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Author-Dedupe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Author-Dedupe.  If not, see <http://www.gnu.org/licenses/>.


nick_names = {
    "Al": "Albert",
    "Andy": "Andrew",
    "Tony": "Anthony",
    "Art": "Arthur",
    "Arty": "Arthur",
    "Bernie": "Bernard",
    "Bern": "Bernard",
    "Charlie": "Charles",
    "Chuck": "Charles",
    "Danny": "Daniel",
    "Dan": "Daniel",
    "Don": "Donald",
    "Ed": "Edward",
    "Eddie": "Edward",
    "Gene": "Eugene",
    "Fran": "Francis",
    "Freddy": "Frederick",
    "Fred": "Frederick",
    "Hank": "Henry",
    "Irv": "Irving",
    "Jimmy": "James",
    "Jim": "James",
    "Joe": "Joseph",
    "Jacky": "John",
    "Jack": "John",
    "Jeff": "Jeffrey",
    "Ken": "Kenneth",
    "Larry": "Lawrence",
    "Leo": "Leonard",
    "Matt": "Matthew",
    "Nate": "Nathan",
    "Nat": "Nathan",
    "Nick": "Nicholas",
    "Pat": "Patrick",
    "Pete": "Peter",
    "Ray": "Raymond",
    "Dick": "Richard",
    "Rick": "Richard",
    "Bob: Bobby: Rob": "Robert",
    "Ron: Ronny": "Ronald",
    "Russ": "Russell",
    "Sam: Sammy": "Samuel",
    "Steve": "Stephan",
    "Stu": "Stuart",
    "Teddy": "Theodore",
    "Ted": "Theodore",
    "Tom": "Thomas",
    "Thom": "Thomas",
    "Tommy": "Thomas",
    "Timmy": "Timothy",
    "Tim": "Timothy",
    "Walt": "Walter",
    "Wally": "Walter",
    "Bill": "William",
    "Billy": "William",
    "Will": "William",
    "Willy": "William",
    "Mandy": "Amanda",
    "Cathy": "Catherine",
    "Cath": "Catherine",
    "Chris": "Christopher",
    "Chrissy": "Christine",
    "Cindy: Cynth": "Cynthia",
    "Debbie": "Deborah",
    "Deb": "Deborah",
    "Betty": "Elizabeth",
    "Beth": "Elizabeth",
    "Liz": "Elizabeth",
    "Bess": "Elizabeth",
    "Flo": "Florence",
    "Francie": "Frances",
    "Fran": "Frances",
    "Jan": "Janet",
    "Kate": "Katherine",
    "Kathy": "Katherine",
    "Jan": "Janice",
    "Nan": "Nancy",
    "Pam": "Pamela",
    "Pat": "Patricia",
    "Bobbie": "Roberta",
    "Sophie": "Sophia",
    "Sue": "Susan",
    "Suzie": "Susan",
    "Terry": "Teresa",
    "Val": "Valerie",
    "Ronnie": "Veronica",
    "Vonna": "Yvonne",
}
